#!/usr/bin/env python3
"""
Compile GLSL shaders to SPIR-V and generate a C++ header with embedded bytecode.

Usage:
    python3 compile_shaders.py [--shader-dir shaders] [--output include/shaders_embedded.h]

The script looks for glslangValidator in this order:
    1. --glslang-validator argument
    2. ANDROID_NDK_HOME environment variable
    3. PATH

For release builds, the generated header is included by VulkanDevice.cpp so
the SPIR-V is linked directly into the .so. For dev/debug builds, the same
header can be regenerated at every build; ENGIN_DEV_SHADER_HOTLOAD also
enables Engine::LoadShaderAsset() which reads .spv from the APK's assets/
folder at runtime for fast iteration without rebuilding native code.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path


def find_glslang_validator(explicit_path=None):
    if explicit_path and os.path.isfile(explicit_path):
        return explicit_path

    ndk = os.environ.get("ANDROID_NDK_HOME")
    if ndk:
        candidate = os.path.join(
            ndk,
            "toolchains", "llvm", "prebuilt",
            "linux-x86_64", "bin", "glslangValidator",
        )
        if os.path.isfile(candidate):
            return candidate

    from shutil import which
    found = which("glslangValidator")
    if found:
        return found

    print(
        "ERROR: glslangValidator not found. Install the Android NDK (r23+) "
        "and set ANDROID_NDK_HOME, or pass --glslang-validator.",
        file=sys.stderr,
    )
    sys.exit(1)


def compile_shader(glslang, input_path, output_path):
    cmd = [
        glslang,
        "-V",                  # Vulkan mode -> SPIR-V
        "--source-entrypoint", "main",
        "-o", str(output_path),
        str(input_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  FAILED: {input_path}\n{result.stderr}", file=sys.stderr)
        return False
    return True


def xxd_style_header(spv_path, var_name, words_var):
    """Read .spv file and return C++ byte-array initializer lines."""
    data = spv_path.read_bytes()
    words = []
    for i in range(0, len(data), 4):
        chunk = data[i:i+4]
        if len(chunk) == 4:
            val = int.from_bytes(chunk, byteorder="little")
            words.append(f"    0x{val:08x}u")
        else:
            # Pad last word
            chunk = chunk.ljust(4, b"\x00")
            val = int.from_bytes(chunk, byteorder="little")
            words.append(f"    0x{val:08x}u  // padding")

    lines = [
        f"// Auto-generated by compile_shaders.py — do not edit.",
        f"// Source: {spv_path.name}",
        f"const uint32_t {var_name}[] = {{",
    ]
    lines.extend(words)
    lines.append(f"}};")
    lines.append(f"const size_t {words_var} = sizeof({var_name}) / sizeof({var_name}[0]);")

    # Pointer alias so callers can write `kFullscreenVertSpirv` / `kFullscreenVertSpirvWords`
    # matching the original RenderGraph convention. inline avoids multiple-definition
    # errors when this header is included from multiple .cpp files.
    ptr_name = f"{var_name}Spirv"
    lines.append(f"inline const uint32_t* {ptr_name} = {var_name};")
    lines.append(f"inline const size_t {ptr_name}Words = {words_var};")
    return "\n".join(lines)


def to_camel_case(snake_str):
    """Convert snake_case to CamelCase."""
    return "".join(word.capitalize() for word in snake_str.split("_"))

def main():
    parser = argparse.ArgumentParser(description="Compile GLSL shaders to embedded SPIR-V header")
    parser.add_argument("--shader-dir", default="src/main/cpp/shaders",
                        help="Directory containing .vert/.frag GLSL files")
    parser.add_argument("--output", default="src/main/cpp/shaders_embedded.h",
                        help="Output C++ header path")
    parser.add_argument("--glslang-validator", default=None,
                        help="Path to glslangValidator binary")
    args = parser.parse_args()

    glslang = find_glslang_validator(args.glslang_validator)
    print(f"Using glslangValidator: {glslang}")

    shader_dir = Path(args.shader_dir)
    if not shader_dir.is_dir():
        print(f"ERROR: shader directory not found: {shader_dir}", file=sys.stderr)
        sys.exit(1)

    # Discover shaders
    shaders = sorted(shader_dir.glob("*.vert")) + sorted(shader_dir.glob("*.frag"))
    if not shaders:
        print(f"WARNING: no .vert/.frag files found in {shader_dir}", file=sys.stderr)

    # Compile to temp .spv files and collect definitions
    generated_arrays = []

    for shader_path in shaders:
        stem = shader_path.stem  # e.g. "blend_normal"
        suffix = shader_path.suffix  # ".vert" or ".frag"
        spv_path = shader_path.with_suffix(".spv")
        var_suffix = "Vert" if suffix == ".vert" else "Frag"
        var_name = f"k{to_camel_case(stem)}{var_suffix}"
        words_var = f"k{to_camel_case(stem)}{var_suffix}Words"

        print(f"Compiling {shader_path.name} -> {spv_path.name}")
        if not compile_shader(glslang, shader_path, spv_path):
            continue

        header_content = xxd_style_header(spv_path, var_name, words_var)
        generated_arrays.append(header_content)

    # Write output header
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by compile_shaders.py. Do not edit.\n")
        f.write("// Rebuild this file whenever a .vert/.frag shader changes.\n\n")
        for arr in generated_arrays:
            f.write(arr + "\n\n")

    print(f"\nGenerated: {output_path} ({len(declarations)} shaders)")


if __name__ == "__main__":
    main()
